name: Build dynmap for Akashic MC
# By Myth, created for Akashic MC


on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew --refresh-dependencies && ./gradlew clean build

    - uses: actions/upload-artifact@v2
      with:
        name: Dynmap-spigot.jar
        path: target/*spigot.jar
    
    - uses: actions/upload-artifact@v2
      with:
        name: Dynmap-spigot.jar.MD5
        path: target/*spigot.jar.MD5
